services:
  nats-server:
    image: nats:latest
    ports:
      - "8222:8222"

  ms-gateway:
    build: ./ms-gateway
    ports:
      - ${MS_GATEWAY_PORT}:3000
    volumes:
      - ./ms-gateway/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=3000
      - NATS_SERVERS=nats://nats-server:4222

  ms-products:
    build: ./ms-products
    ports:
      - "3001:3001"
    volumes:
      - ./ms-products/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=3001
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=file:./dev.db

  ms-orders:
    build: ./ms-orders
    ports:
      - "3002:3002"
    volumes:
      - ./ms-orders/src:/usr/src/app/src
    command: npm run start:dev
    depends_on:
      - orders-db
    environment:
      - PORT=3002
      - DATABASE_URL=postgresql://postgres:123456@orders-db:5432/ordersDB?schema=public
      - NATS_SERVERS=nats://nats-server:4222

  orders-db:
    image: postgres:16.2
    restart: always
    volumes:
      - ./ms-orders/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=ordersDB

  ms-payments:
    build: ./ms-payments
    ports:
      - ${MS_PAYMENTS_PORT}:3003
    volumes:
      - ./ms-payments/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=${MS_PAYMENTS_PORT}
      - NATS_SERVERS=${NATS_SERVERS}
      - STRIPE_SECRET=${STRIPE_SECRET}
      - STRIPE_SUCCESS_URL=${STRIPE_SUCCESS_URL}
      - STRIPE_CANCEL_URL=${STRIPE_CANCEL_URL}
      - STRIPE_ENDPOINT_SECRET=${STRIPE_ENDPOINT_SECRET}