apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: ms-gateway
  name: ms-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-gateway
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ms-gateway
    spec:
      containers:
      - image: 590183920340.dkr.ecr.us-east-1.amazonaws.com/tienda-microservices/image-registry:ms-gateway
        name: image-registry
        env:
          - name: PORT
            value: "3000"
          - name: NATS_SERVERS
            value: "nats://nats"
        resources: {}
status: {}
